# -*- coding: utf-8 -*-
"""Plot_S8_Muñoz_Escobar_Daniel_Arukin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pXOM_Uk17K1skfaoZWBO2EC6GKwsxan
"""

import numpy as np
import matplotlib.pylab as plt

#Ecuaciones diferenciales parciales: diferenciales finitas ecuación de onda 1D
datos_de_la_onda=np.genfromtxt("Posiciones de la cuerda",dtype=None,delimiter='|')
x=np.linspace(0, 100, 100, endpoint=True)

y=datos_de_la_onda[0:100]

matriz_de_onda=(np.random.random((100,3002)))
contador=0

for i in range(0,3002):
  for j in range(0,100):
    matriz_de_onda[j][i]=datos_de_la_onda[contador,0]

  contador+=1
print(matriz_de_onda)

print(contador)
plt.figure()
plt.title('Movimiento de una cuerda de una guitarra', fontsize=12)
for k in range(0,3002):
  plt.plot(x,matriz_de_onda[:,k])
plt.savefig("Movimiento de una cuerda de una guitarra.pdf")

#traté de agarrar los datos y organizarlos en una matriz para que

plt.figure()
plt.title('Movimiento de una cuerda de una guitarra 2', fontsize=12)
plt.plot(x,datos_de_la_onda[100:200,0],'g')
plt.savefig("Movimiento de una cuerda de una guitarra 2.pdf")